name: Deploy to AWS

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  deploy_to_aws:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the application's source code
        uses: actions/checkout@v2

      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com
          scope: "@university-of-york"
          always-auth: true

      - name: Install application dependencies
        run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Check code is formatted correctly
        run: npm run checkformat

      - name: Check code conforms to linting rules
        run: npm run lint

      - name: Check tests run
        run: npm run test

      - name: Deploy - dev
        if: github.ref == 'refs/heads/dev'
        run: npm run deploy:dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          DEPLOY_ENVIRONMENT: dev
          SSL_CERTIFICATE_ARN: ${{ secrets.DEV_SSL_CERTIFICATE_ARN }}
          DOMAIN_NAME: courses.dev.app.york.ac.uk

      - name: Deploy - production
        if: github.ref == 'refs/heads/main'
        run: npm run deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.PRODUCTION_AWS_ACCOUNT_ID }}
          DEPLOY_ENVIRONMENT: prod
          SSL_CERTIFICATE_ARN: ${{ secrets.PRODUCTION_SSL_CERTIFICATE_ARN }}
          DOMAIN_NAME: courses.app.york.ac.uk

      - name: Deploy - google optimize experiment
        if: github.ref == 'refs/heads/CFIN-453'
        run: npm run deploy:dev
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.DEV_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.DEV_AWS_SECRET_ACCESS_KEY }}
          AWS_ACCOUNT_ID: ${{ secrets.DEV_AWS_ACCOUNT_ID }}
          DEPLOY_ENVIRONMENT: dev
          SSL_CERTIFICATE_ARN: arn:aws:acm:eu-west-1:098107509664:certificate/73e0eef3-636b-4555-ab14-7c9b6e73937e
          DOMAIN_NAME: courses.googleoptimize.dev.app.york.ac.uk
